// <auto-generated />
using System;
using HacknetSharp.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace hspostgres.Migrations
{
    [DbContext(typeof(ServerStorageContext))]
    partial class ServerStorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.FolderModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("World")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("OwnerKey");

                    b.ToTable("FolderModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PersonModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerKey")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("World")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("PlayerKey");

                    b.ToTable("PersonModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PlayerModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<Guid>("ActiveWorld")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentSystemKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefaultSystem")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("CurrentSystemKey");

                    b.ToTable("PlayerModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SimpleFileModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerKey")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("World")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("OwnerKey");

                    b.ToTable("SimpleFileModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SystemModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerKey")
                        .HasColumnType("uuid");

                    b.Property<Guid>("World")
                        .HasColumnType("uuid");

                    b.HasKey("Key");

                    b.HasIndex("OwnerKey");

                    b.ToTable("SystemModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.RegistrationToken", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("RegistrationToken");
                });

            modelBuilder.Entity("HacknetSharp.Server.UserModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<bool>("Admin")
                        .HasColumnType("boolean");

                    b.Property<string>("Base64Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Base64Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.FolderModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.SystemModel", "Owner")
                        .WithMany("Folders")
                        .HasForeignKey("OwnerKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PersonModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.PlayerModel", "Player")
                        .WithMany("Identities")
                        .HasForeignKey("PlayerKey");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PlayerModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.SystemModel", "CurrentSystem")
                        .WithMany()
                        .HasForeignKey("CurrentSystemKey");

                    b.Navigation("CurrentSystem");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SimpleFileModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.SystemModel", "Owner")
                        .WithMany("SimpleFiles")
                        .HasForeignKey("OwnerKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SystemModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.PersonModel", "Owner")
                        .WithMany("Systems")
                        .HasForeignKey("OwnerKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PersonModel", b =>
                {
                    b.Navigation("Systems");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PlayerModel", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SystemModel", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("SimpleFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
