// <auto-generated />
using System;
using HacknetSharp.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace hssqlite.Migrations
{
    [DbContext(typeof(ServerStorageContext))]
    [Migration("20201129085229_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.FileModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AdminExecute")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdminRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdminWrite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SystemKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorldKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("OwnerKey");

                    b.HasIndex("SystemKey");

                    b.HasIndex("WorldKey");

                    b.ToTable("FileModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.LoginModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("PersonForeignKey")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<Guid>("SystemKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorldKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("PersonForeignKey")
                        .IsUnique();

                    b.HasIndex("SystemKey");

                    b.HasIndex("WorldKey");

                    b.ToTable("LoginModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PersonModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentSystemKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultSystemKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("CurrentSystemKey");

                    b.HasIndex("DefaultSystemKey");

                    b.HasIndex("PlayerKey");

                    b.HasIndex("WorldKey");

                    b.ToTable("PersonModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PlayerModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActiveWorld")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserForeignKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("UserForeignKey")
                        .IsUnique();

                    b.ToTable("PlayerModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.RegistrationToken", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForgerKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("ForgerKey");

                    b.ToTable("RegistrationToken");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SystemModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialProgram")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OsName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerKey")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorldKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("OwnerKey");

                    b.HasIndex("WorldKey");

                    b.ToTable("SystemModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.UserModel", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Key");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.WorldModel", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerSystemTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartupCommandLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartupProgram")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("WorldModel");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.FileModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.LoginModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerKey");

                    b.HasOne("HacknetSharp.Server.Common.Models.SystemModel", "System")
                        .WithMany("Files")
                        .HasForeignKey("SystemKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HacknetSharp.Server.Common.Models.WorldModel", "World")
                        .WithMany()
                        .HasForeignKey("WorldKey");

                    b.Navigation("Owner");

                    b.Navigation("System");

                    b.Navigation("World");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.LoginModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.PersonModel", "Person")
                        .WithOne("CurrentLogin")
                        .HasForeignKey("HacknetSharp.Server.Common.Models.LoginModel", "PersonForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HacknetSharp.Server.Common.Models.SystemModel", "System")
                        .WithMany("Logins")
                        .HasForeignKey("SystemKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HacknetSharp.Server.Common.Models.WorldModel", "World")
                        .WithMany()
                        .HasForeignKey("WorldKey");

                    b.Navigation("Person");

                    b.Navigation("System");

                    b.Navigation("World");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PersonModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.SystemModel", "CurrentSystem")
                        .WithMany()
                        .HasForeignKey("CurrentSystemKey");

                    b.HasOne("HacknetSharp.Server.Common.Models.SystemModel", "DefaultSystem")
                        .WithMany()
                        .HasForeignKey("DefaultSystemKey");

                    b.HasOne("HacknetSharp.Server.Common.Models.PlayerModel", "Player")
                        .WithMany("Identities")
                        .HasForeignKey("PlayerKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HacknetSharp.Server.Common.Models.WorldModel", "World")
                        .WithMany("Persons")
                        .HasForeignKey("WorldKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentSystem");

                    b.Navigation("DefaultSystem");

                    b.Navigation("Player");

                    b.Navigation("World");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PlayerModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.UserModel", "User")
                        .WithOne("Player")
                        .HasForeignKey("HacknetSharp.Server.Common.Models.PlayerModel", "UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.RegistrationToken", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.UserModel", "Forger")
                        .WithMany()
                        .HasForeignKey("ForgerKey");

                    b.Navigation("Forger");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SystemModel", b =>
                {
                    b.HasOne("HacknetSharp.Server.Common.Models.PersonModel", "Owner")
                        .WithMany("Systems")
                        .HasForeignKey("OwnerKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HacknetSharp.Server.Common.Models.WorldModel", "World")
                        .WithMany("Systems")
                        .HasForeignKey("WorldKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("World");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PersonModel", b =>
                {
                    b.Navigation("CurrentLogin");

                    b.Navigation("Systems");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.PlayerModel", b =>
                {
                    b.Navigation("Identities");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.SystemModel", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Logins");
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.UserModel", b =>
                {
                    b.Navigation("Player")
                        .IsRequired();
                });

            modelBuilder.Entity("HacknetSharp.Server.Common.Models.WorldModel", b =>
                {
                    b.Navigation("Persons");

                    b.Navigation("Systems");
                });
#pragma warning restore 612, 618
        }
    }
}
