name: .NET Build

on:
  push:
    branches: [ waifu ]
  pull_request:
    branches: [ waifu ]

defaults:
  run:
    working-directory: src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --framework net6.0 --configuration Release --no-build

    # - name: Publish hsh net5.0 osx-x64
    #   run: dotnet publish hsh --framework net5.0 --configuration Release --runtime osx-x64 --self-contained false
    # - name: Publish hsh net5.0 linux-x64
    #   run: dotnet publish hsh --framework net5.0 --configuration Release --runtime linux-x64 --self-contained false
    # - name: Publish hsh net5.0 win-x64
    #   run: dotnet publish hsh --framework net5.0 --configuration Release --runtime win-x64 --self-contained false

    # - name: Publish hss net5.0 osx-x64
    #   run: dotnet publish hss --framework net5.0 --configuration Release --runtime osx-x64 --self-contained false
    # - name: Publish hss net5.0 linux-x64
    #   run: dotnet publish hss --framework net5.0 --configuration Release --runtime linux-x64 --self-contained false
    # - name: Publish hss net5.0 win-x64
    #   run: dotnet publish hss --framework net5.0 --configuration Release --runtime win-x64 --self-contained false

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: hsh-net5.0-osx-64
    #     path: src/hsh/bin/Release/net5.0/osx-x64/publish/
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: hsh-net5.0-linux-64
    #     path: src/hsh/bin/Release/net5.0/linux-x64/publish/
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: hsh-net5.0-win-64
    #     path: src/hsh/bin/Release/net5.0/win-x64/publish/

    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: hss-net5.0-osx-64
    #     path: src/hss/bin/Release/net5.0/osx-x64/publish/
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: hss-net5.0-linux-64
    #     path: src/hss/bin/Release/net5.0/linux-x64/publish/
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: hss-net5.0-win-64
    #     path: src/hss/bin/Release/net5.0/win-x64/publish/
